# Generated by Django 2.2 on 2019-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hoobang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('count', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
            ],
        ),
    ]
