# Generated by Django 2.2 on 2020-02-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoobangList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hoobang',
            new_name='HoobangList',
        ),
    ]
