# Generated by Django 2.2 on 2019-10-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_choice_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='party_number',
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
