# Generated by Django 2.2 on 2019-11-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20191029_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='party_number',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='area',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
