# Generated by Django 2.2 on 2019-11-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20191103_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
