# Generated by Django 2.2 on 2020-03-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainList', '0002_auto_20200216_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlist',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
